// <auto-generated />
using System;
using BlazorApp.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorMasterDetails.Server.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    partial class PatientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorMasterDetails.Shared.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MaritialStatus")
                        .HasColumnType("bit");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("BlazorMasterDetails.Shared.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"), 1L, 1);

                    b.Property<string>("TestName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestId");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            TestId = 1,
                            TestName = "Serological Test"
                        },
                        new
                        {
                            TestId = 2,
                            TestName = "Blood Test"
                        },
                        new
                        {
                            TestId = 3,
                            TestName = "Pregnancy Test"
                        },
                        new
                        {
                            TestId = 4,
                            TestName = "Syphilis Test"
                        },
                        new
                        {
                            TestId = 5,
                            TestName = "Toxicology Test"
                        },
                        new
                        {
                            TestId = 6,
                            TestName = "Brain Scanning"
                        });
                });

            modelBuilder.Entity("BlazorMasterDetails.Shared.TestEntry", b =>
                {
                    b.Property<int>("TestEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestEntryId"), 1L, 1);

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("TestEntryId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TestId");

                    b.ToTable("TestEntries");
                });

            modelBuilder.Entity("BlazorMasterDetails.Shared.TestEntry", b =>
                {
                    b.HasOne("BlazorMasterDetails.Shared.Patient", "Patient")
                        .WithMany("TestEntries")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorMasterDetails.Shared.Test", "Test")
                        .WithMany("TestEntries")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("BlazorMasterDetails.Shared.Patient", b =>
                {
                    b.Navigation("TestEntries");
                });

            modelBuilder.Entity("BlazorMasterDetails.Shared.Test", b =>
                {
                    b.Navigation("TestEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
